case MESSAGE_ID_NEARBY_LOCALE_REQUEST:
	
	break;
case MESSAGE_ID_NEARBY_LOCALE_RESPONSE:
	
	break;
case MESSAGE_ID_JOIN_PUBLIC_LOCALE_REQUEST:
	
	break;
case MESSAGE_ID_JOIN_PRIVATE_LOCALE_REQUEST:
	
	break;
case MESSAGE_ID_JOIN_LOCALE_RESPONSE:
	
	break;
case MESSAGE_ID_LEAVE_LOCALE_REQUEST:
	
	break;
case MESSAGE_ID_LEAVE_LOCALE_RESPONSE:
	
	break;
case MESSAGE_ID_SEND_TEXT_POST_REQUEST:
	
	break;
case MESSAGE_ID_SEND_IMAGE_POST_REQUEST:
	
	break;
case MESSAGE_ID_SEND_POST_RESPONSE:
	
	break;
case MESSAGE_ID_NEW_TEXT_POST_NOTICE:
	
	break;
case MESSAGE_ID_NEW_IMAGE_POST_NOTICE:
	
	break;
case MESSAGE_ID_CREATE_LOCALE_REQUEST:
	
	break;
case MESSAGE_ID_CREATE_LOCALE_RESPONSE:
	
	break;
case MESSAGE_ID_NICKNAME_SET_REQUEST:
	
	break;
case MESSAGE_ID_NICKNAME_SET_RESPONSE:
	
	break;
